### PR TITLE
Add HTTP basic authentication for admin pages

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Hi @mosen,

Why did you close this PR? I'd appreciate at least a comment.

**Comment by mosen** [comment]
Sorry I'd taken over the codebase and replaced everything so I thought itd be necessary to start fresh. I can reopen it though

**Comment by CyberShadow** [comment]
I see the README no longer mentions lack of authentication as an issue. Is it implemented now?

**Comment by mosen** [comment]
No but the intention is firstly to protect API via jet and then establish sso support

**Pull request closed without merging**
